### ISSUE TITLE
Use core CSS var for admin bar height

### ISSUE THREAD

**Issue by cr0ybot** [BlackbirdDigital/wp-theme-scaffold#50]
Instead of manually setting the admin bar height value, we should use `--wp-admin--admin-bar--height` with a fallback to `0px`.

```css
:root {
	// When admin bar is not shown, default to 0px.
	--global--admin-bar--height: var(--wp-admin--admin-bar--height, 0px);
}
```
